# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
- task: BeanstalkDeployApplication@1
  inputs:
    awsCredentials: 'cicd_proyecto'
    regionName: 'us-east-1'
    applicationName: 'cicd_blockchain'
    environmentName: 'Cicdblockchain-env-1'
    applicationType: 's3'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
